{% set component_name = "tools" %}
{% set repo_name = "gz-" + component_name %}
{% set version = "2.0.1" %}
{% set major_version = version.split('.')[0] %}
{% set name = repo_name + major_version %}
{% set component_version = component_name + major_version %}
{% set cxx_name = "lib" + name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gazebosim/{{ repo_name }}/archive/{{ repo_name }}{{ major_version }}_{{ version }}.tar.gz
    sha256: 93c1f6e91ae82671d66b55929aff07f89df7ac20182d8bca44a2f7204792725c
    patches:
      - fix_backward_install.patch

build:
  number: 0

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
      ignore_run_exports:
        - ruby
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - ninja
        - cmake
        - pkg-config
      host:
        - libgz-cmake3
        - backward-cpp
        - ruby
      run:
        - ruby
        - elfutils                           # [linux]
    test:
      commands:
        - test -f ${PREFIX}/lib/cmake/{{ name }}-all/{{ name }}-all-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}-all\\{{ name }}-all-config.cmake exit 1  # [win]

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/cmake/{{ name }}-all/{{ name }}-all-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}-all\\{{ name }}-all-config.cmake exit 1  # [win]


about:
  home: https://github.com/gazebosim/gz-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Command line tools for the Gazebo libraries.

extra:
  feedstock-name: {{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - j-rivero
